daftar_unduhan/urls.py
from django.urls import path
from daftar_unduhan.views import show_daftar_unduhan, add_daftar_unduhan, delete_daftar_unduhan

app_name = 'daftar_unduhan'

urlpatterns = [
    path('', show_daftar_unduhan, name='show_daftar_unduhan'),
    path('add-daftar-unduhan/<str:id_tayangan>', add_daftar_unduhan, name='add_daftar_unduhan'),
    path('delete-daftar-unduhan/<str:id_tayangan>', delete_daftar_unduhan, name='delete_daftar_unduhan'),
]

langganan/urls.py
from django.urls import path

from . import views

app_name = 'langganan'

urlpatterns = [
    path('', views.index, name='index'),
    path('beli/', views.beli, name='beli')
]

pacilflix/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daftar-favorit/', include('daftar_favorit.urls')),
    path('daftar-unduhan/', include('daftar_unduhan.urls')),
    path('langganan/', include('langganan.urls')),
    path('kontributor/', include('kontributor.urls')),
    path('fakhri-hijau/', include('fakhri_hijau.urls')),
    path('auth/', include('authentication.urls')),
    path('', RedirectView.as_view(url='/fakhri-hijau/tayangan', permanent=False)),
]

daftar_unduhan/models.py
from django.db import models

# Create your models here.

daftar_unduhan/views.py
from datetime import datetime
from django.shortcuts import redirect, render

from utils import DatabaseConnection

def show_daftar_unduhan(request):
    # verify login
    if 'user' not in request.session:
        return redirect("/auth")
    context = {'authenticated' : True, 'user' : request.session['user']}

    username = request.session['user']['username']
    select_query = f"SELECT timestamp, judul, id_tayangan FROM TAYANGAN_TERUNDUH TT JOIN TAYANGAN T ON TT.id_tayangan = T.id WHERE TT.username = '{username}'"

    database = DatabaseConnection()
    daftar_unduhan = database.query(select_query)

    context['daftar_unduhan'] = daftar_unduhan

    return render(request, 'daftar_unduhan.html', context)

def add_daftar_unduhan(request, id_tayangan):
    # verify login
    if 'user' not in request.session:
        return redirect("/auth")
    context = {'authenticated' : True, 'user' : request.session['user']}

    username = request.session['user']['username']

    database = DatabaseConnection()
    select_query = f"SELECT * FROM TAYANGAN_TERUNDUH TT WHERE TT.username = '{username}' AND TT.id_tayangan = '{id_tayangan}'"
    daftar_unduhan = database.query(select_query)

    if not daftar_unduhan:
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
        insert_query = f"INSERT INTO TAYANGAN_TERUNDUH VALUES('{id_tayangan}','{username}','{timestamp}');"
        database.query(insert_query)
    
    return redirect('/fakhri-hijau/tayangan')

def delete_daftar_unduhan(request, id_tayangan):
    # verify login
    if 'user' not in request.session:
        return redirect("/auth")
    context = {'authenticated' : True, 'user' : request.session['user']}

    username = request.session['user']['username']
    delete_query = f"DELETE FROM TAYANGAN_TERUNDUH TT WHERE TT.username = '{username}' AND TT.id_tayangan = '{id_tayangan}'"

    database = DatabaseConnection()
    database.query(delete_query)

    return redirect("/daftar-unduhan")

daftar_unduhan/templates/daftar_unduhan.html
{% extends 'base.html' %} 

{% block meta %}
    {{ block.super }}
        <title>Pacilflix - Daftar Unduhan</title>
{% endblock meta %} 

{% block content %}
    {{ block.super }}
        <h1
            class="m-4 text-4xl font-bold leading-none tracking-tight text-gray-900 md:text-4xl lg:text-5xl dark:text-gray-900 text-center">
            Daftar Unduhan
        </h1>

        <div class="m-4 relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Judul
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Waktu Diunduh
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Aksi
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% if daftar_unduhan %}
                        {% for unduhan in daftar_unduhan %}
                            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                    {{ unduhan.judul }}
                                </th>
                                <td class="px-6 py-4">
                                    {{ unduhan.timestamp }}
                                </td>
                                <td class="px-6 py-4">
                                    <a href="{% url 'daftar_unduhan:delete_daftar_unduhan' unduhan.id_tayangan %}">
                                        Hapus
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <p class="h6">- Anda belum menambahkan tayangan ke daftar favorit -</p>
                    {% endif %}
                </tbody>
            </table>
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
{% endblock content %}