daftar_favorit/urls.py
from django.urls import path
from daftar_favorit.views import delete_daftar_favorit, show_daftar_favorit, add_daftar_favorit

app_name = 'daftar_favorit'

urlpatterns = [
    path('', show_daftar_favorit, name='show_daftar_favorit'),
    path('add-daftar-favorit/<str:judul>', add_daftar_favorit, name='add_daftar_favorit'),
    path('delete-daftar-favorit/<str:judul>', delete_daftar_favorit, name='delete_daftar_favorit')
]

langganan/urls.py
from django.urls import path

from . import views

app_name = 'langganan'

urlpatterns = [
    path('', views.index, name='index'),
    path('beli/', views.beli, name='beli')
]

pacilflix/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daftar-favorit/', include('daftar_favorit.urls')),
    path('daftar-unduhan/', include('daftar_unduhan.urls')),
    path('langganan/', include('langganan.urls')),
    path('kontributor/', include('kontributor.urls')),
    path('fakhri-hijau/', include('fakhri_hijau.urls')),
    path('auth/', include('authentication.urls')),
    path('', RedirectView.as_view(url='/fakhri-hijau/tayangan', permanent=False)),
]

daftar_favorit/models.py
from django.db import models

# Create your models here.

daftar_favorit/views.py
from datetime import datetime
from django.shortcuts import redirect, render

from utils import DatabaseConnection

def show_daftar_favorit(request):
    # verify login
    if 'user' not in request.session:
        return redirect("/auth")
    context = {'authenticated' : True, 'user' : request.session['user']}

    username = request.session['user']['username']
    query = f"SELECT * FROM DAFTAR_FAVORIT DF WHERE DF.username = '{username}'"
    
    database = DatabaseConnection()
    daftar_favorit = database.query(query)

    context['daftar_favorit'] = daftar_favorit
    
    return render(request, 'daftar_favorit.html', context)

def add_daftar_favorit(request, judul):
    # verify login
    if 'user' not in request.session:
        return redirect("/auth")
    context = {'authenticated' : True, 'user' : request.session['user']}

    username = request.session['user']['username']
    select_query = f"SELECT * FROM DAFTAR_FAVORIT DF WHERE DF.username = '{username}' AND DF.judul = '{judul}'"

    database = DatabaseConnection()
    daftar_favorit = database.query(select_query)

    if not daftar_favorit:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        insert_query = f"INSERT INTO DAFTAR_FAVORIT (timestamp, username, judul) VALUES('{timestamp}', '{username}', '{judul}')"

        database.query(insert_query)

    return redirect("/fakhri-hijau/tayangan")

def delete_daftar_favorit(request, judul):
    # verify login
    if 'user' not in request.session:
        return redirect("/auth")
    context = {'authenticated' : True, 'user' : request.session['user']}

    username = request.session['user']['username']
    delete_query = f"DELETE FROM DAFTAR_FAVORIT DF WHERE DF.username = '{username}' AND DF.judul = '{judul}'"

    database = DatabaseConnection()
    database.query(delete_query)

    return redirect("/daftar-favorit")

daftar_favorit/templates/daftar_favorit.html
{% extends 'base.html' %} 

{% block meta %}
    {{ block.super }}
        <title>Pacilflix - Daftar Favorit</title>
{% endblock meta %} 

{% block content %}
    {{ block.super }}
        <h1
            class="m-4 text-4xl font-bold leading-none tracking-tight text-gray-900 md:text-4xl lg:text-5xl dark:text-gray-900 text-center">
            Daftar Favorit
        </h1>

        <div class="m-4 relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Judul
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Waktu Dibuat
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Aksi
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% if daftar_favorit %}
                        {% for favorit in daftar_favorit %}
                            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                    {{ favorit.judul }}
                                </th>
                                <td class="px-6 py-4">
                                    {{ favorit.timestamp }}
                                </td>
                                <td class="px-6 py-4">
                                    <a href="{% url 'daftar_favorit:delete_daftar_favorit' favorit.judul %}">
                                        Hapus Favorit
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <p class="h6">- Anda belum menambahkan tayangan ke daftar favorit -</p>
                    {% endif %}
                </tbody>
            </table>
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
{% endblock content %}